name: Pull Request Labeler

on:
  pull_request:
    branches: ["*"]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get base branch
        id: base
        run: echo "::set-output name=base_branch::$(git rev-parse --abbrev-ref HEAD)"
      - name: Label pull request
        if: steps.base.outputs.base_branch == 'main'
        run: |
          git remote set-branches --add origin main
          git fetch
          git checkout main
          git merge dev
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add "Ship to Production" label
        if: steps.base.outputs.base_branch == 'main'
        uses: peter-evans/create-and-apply-label@v2
        with:
          label: "Ship to Production"
          color: "0052cc"
      - name: Add "Invalid" label
        if: steps.base.outputs.base_branch != 'main'
        uses: peter-evans/create-and-apply-label@v2
        with:
          label: "Invalid"
          color: "e11d21"
