name: Pull Request Labeler

on:
  pull_request:
    branches: ["*"]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check pull request destination branch
        run: |
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            LABEL="Ship to Production"
          else
            LABEL="invalid"
          fi
      - name: Add label to pull request
        uses: octokit/request-action@v2
        with:
          route: POST /repos/:owner/:repo/issues/:issue_number/labels
          payload: '{"labels": ["${{LABEL}}"]}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
